version: '3'
services:
  nextjs:
    build: ./
    env_file:
      - production.env
    volumes:
      - ./next-cache:/usr/app/.next/cache/:rw,Z 
  nginx:
    build: ./nginx
    ports:
      - 83:80
volumes:
  next-cache: {}
