version: '3'

services:

  web:
    restart: always
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9600:80"

  nginx:  
    restart: always
    image: nginx
    environment: 
      - PANGO_CAIRO_ENABLED=0
      - PANGO_FREETYPE_ENABLED=0
    ports:
      - "3000:80"
    volumes: 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/html:ro

volumes:
  node_modules: {}
